package de.dhbw.td.core.ui;

public enum EUserAction {
	NONE,
	PAUSE_GAME,
	NEW_GAME, 
	RESUME_GAME,
	QUIT_GAME, 
	MAIN_MENU, 
	INAGAME_MENU, 
	NEW_MATH_TOWER,
	NEW_CODE_TOWER, 
	NEW_TECH_INF_TOWER, 
	NEW_THEO_INF_TOWER, 
	NEW_ECO_TOWER, 
	NEW_SOCIAL_TOWER;
}